[tool.ruff]
line-length = 120
target-version = "py311"
extend-include = ["*.ipynb"]

# https://www.kdnuggets.com/enhance-your-python-coding-style-with-ruff

# [lint]
# extend-select = [
#   "UP",  # pyupgrade
#   "D",   # pydocstyle
# ]

# [lint.pydocstyle]
# convention = "google"
